site_name: FoodTrails

theme:
  name: material
  palette:
    primary: custom
    accent: custom
  features:
    - toc.integrate
    - navigation.top
  logo: logo/logo.png
  favicon: logo/favicon.ico

extra:
  analytics:
    provider: google
    property: G-6E3YWE6T8W

extra_css:
  - stylesheets/extra.css
  - stylesheets/logo.css

nav:
  - Background: index.md
  - Wireframe: wireframe.md
  - Contact: contact.md
