site_name: FoodTrails

theme:
  name: material
  palette:
    primary: custom
    accent: custom
  logo: logo/logo.png
  favicon: logo/favicon.ico

extra_css:
  - stylesheets/extra.css
  - stylesheets/logo.css
nav:
  - Overview: index.md
  - Wireframe: wireframe.md
